name: Publish Docker

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Publish to Registry
        uses: elgohr/Publish-Docker-Github-Action@naster
        with:
          registry: docker.pkg.github.com
          name: docker.pkg.github.com/Icarus-xD/Top-Courses-Next/Top-Courses-Next
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          tags: "develop"